// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_drcTMB_TMBExports
#include <TMB.hpp>
#include "drcL5.hpp"
#include "drcL5fix.hpp"
#include "drcL5pois.hpp"
#include "drcL5poisfix.hpp"
#include "drcL5binom.hpp"
#include "drcL5binomfix.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "drcL5") {
    return drcL5(this);
  } else if(model == "drcL5fix") {
    return drcL5fix(this);
  } else if(model == "drcL5pois") {
    return drcL5pois(this);
  } else if(model == "drcL5poisfix") {
    return drcL5poisfix(this);
  } else if(model == "drcL5binom") {
    return drcL5binom(this);
  } else if(model == "drcL5binomfix") {
    return drcL5binomfix(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
